### ISSUE TITLE
User session keeps expiring - User session has been expired, please Sign in again

### ISSUE THREAD

**Issue by StarAzure** [feednext/feednext#80]
User session expires in less than 60 seconds. 

This message seems to come from antd - 
_User session has been expired, please Sign in again_

`createError
file:/C:/site/client/.next/static/development/pages/auth/sign-in.js (58034:15)
handleAbort
/_next/static/development/pages/auth/sign-in.js (57515:14)`

**Comment by ozkanonur** [comment]
Clear localstorage and cache and check it again, meanwhile I will try to find what makes it happen. I never meet with that problem before. You getting this issue on your local machine or production ?

**Comment by StarAzure** [comment]
@ozkanonur Cleared everything and also tried a different browser (chrome). Also tried the new Edge browser (using for first time) - The session expires on all browsers.

I am doing this on local - Windows 10.

**Comment by ozkanonur** [comment]
@StarAzure  Did you check the request responses to see they are hitting to correct address ? I am guessing you have incorrect values in [constants.ts](https://github.com/feednext/feednext/blob/master/client/config/constants.ts)

**Comment by StarAzure** [comment]
@ozkanonur I have it just like the documentation:

`export const API_URL = process.env.NODE_ENV === 'production' ? 'https://server.feednext.io/api' : 'http://localhost:3000/api'
export const SOCKET_URL = process.env.NODE_ENV === 'production' ? 'https://server.feednext.io' : 'http://localhost:4001'`

**Comment by StarAzure** [comment]
@ozkanonur Just wondering if you have any suggestions. This keeps happening consistently and I am unable to make any progress.

**Comment by ozkanonur** [comment]
@StarAzure Please show me your XHR requests with responses

**Comment by StarAzure** [comment]
@ozkanonur - Please see below

![image](https://user-images.githubusercontent.com/12852059/87861844-3bece380-c918-11ea-8616-cc45b40a14ad.png)

**Comment by ozkanonur** [comment]
@StarAzure show me the responses. Go localhost:8000 and show me the responses of the requests.

**Comment by StarAzure** [comment]
@ozkanonur I meant to show you but looks like it logged out last time. 

![image](https://user-images.githubusercontent.com/12852059/87862032-c1bd5e80-c919-11ea-842d-2c8f9d5b896a.png)

**Comment by ozkanonur** [comment]
@StarAzure there is still no response informations in screenshots, its only list of the requests. You can see when the app redirects you to login screen. There are no issues on production, and many of the development environments on multiple OS.

**Comment by StarAzure** [comment]
@ozkanonur 
I see a couple of errors:
`Firefox can’t establish a connection to the server at ws://localhost:4001/socket.io/?Authorization=Bearer`

And this is the screen when the redirect after automatic logout looks
![image](https://user-images.githubusercontent.com/12852059/87862319-a738b480-c91c-11ea-8c78-229bcc780586.png)

**Comment by ozkanonur** [comment]
@StarAzure  I cant help if I cant get the right answers. Please search about http protocol on the internet

**Comment by ozkanonur** [comment]
This issue has been closed. Caused by insufficient explanation.

**Comment by StarAzure** [comment]
I know about http protocol. The problem is that its all 200

![image](https://user-images.githubusercontent.com/12852059/87862475-a0ab3c80-c91e-11ea-8276-a666c51949f3.png)

**Comment by dany-eudes** [comment]
I'm facing this issue.
My environment is also Windows 10.

The login process by the admin user occurs as usual. However, after a minute it is possible to quickly see the expired session message followed by redirection to the login page.

See this relevant message in the console log:
`Access to XMLHttpRequest at 'http://localhost:3000/api/v1/auth/check-token' from origin 'http://localhost:8000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

I believe this might likely be that Chrome does not support localhost to go through the Access-Control-Allow-Origin. 

To have Chrome send Access-Control-Allow-Origin in the header, just alias your localhost in your /etc/hosts file to some other domain, like:

127.0.0.1   localhost yourdomain.com

For windows users,  the `hosts` file is in `C:\Windows\System32\drivers\etc`.

There will be more problems for Windows users or others that  they are adding Port numbers to URLs in constants.ts. CORS will fail because these are different origins.

See more info here: https://davidsekar.com/asp-net/cors-development-in-localhost

**Comment by dany-eudes** [comment]
I'm testing a solution as following and it seems to solve the issue for the development environment.

Change the CORS lines in `server/src/ main.ts`

```javascript
fastifyAdapter.enableCors ({
        methods: ['GET', 'HEAD', 'PUT', 'PATCH', 'POST', 'DELETE', 'OPTIONS'],
        credentials: true,
        allowedHeaders: [
            '*',
            'Access-Control-Allow-Headers',
            'source',
            'Content type',
            'Accept',
            'x-requested with',
            'x-requested by',
            'Authorization',
             // put others here if you need... 
        ],
        origin: configService.isProduction ()
            ? configService.getEnv ('APP_DOMAIN')
            : [
                  'capacitor://localhost',
                  'ionic://localhost',
                  'http://localhost',
                  'http://localhost:8000',
                  'http://localhost:3000',
                  'http://localhost:4001',
                  'http://fednext.dev:3000',   // if you use a alias domain in your host file
                  'http://fednext.dev:4001',
                   /^http:\/\/fednext.dev(:\d+)?$/,   // Maybe you could use a regex expression
              ],
       
    })
```

During these tests I also change this first lines:

```` javascript
   const fastifyAdapter = new FastifyAdapter({
        logger: configService.isProduction() ? false : true,
        trustProxy: '127.0.0.1, 192.168.99.1/24', // <-- here 
    }) 
````

But for now I can't tell you if they're really needed or if this is the true solution! ;)
